/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fmod_example_EffectUtils */

#ifndef _Included_org_fmod_example_EffectUtils
#define _Included_org_fmod_example_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef org_fmod_example_EffectUtils_MODE_NORMAL
#define org_fmod_example_EffectUtils_MODE_NORMAL 0L
#undef org_fmod_example_EffectUtils_MODE_LUOLI
#define org_fmod_example_EffectUtils_MODE_LUOLI 1L
#undef org_fmod_example_EffectUtils_MODE_DASHU
#define org_fmod_example_EffectUtils_MODE_DASHU 2L
#undef org_fmod_example_EffectUtils_MODE_JINGSONG
#define org_fmod_example_EffectUtils_MODE_JINGSONG 3L
#undef org_fmod_example_EffectUtils_MODE_GAOGUAI
#define org_fmod_example_EffectUtils_MODE_GAOGUAI 4L
#undef org_fmod_example_EffectUtils_MODE_KONGLING
#define org_fmod_example_EffectUtils_MODE_KONGLING 5L
/*
 * Class:     org_fmod_example_EffectUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_fmod_example_EffectUtils_fix
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_fmod_example_EffectUtils
 * Method:    stopPaly
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fmod_example_EffectUtils_stopPaly
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
